---
language: ruby
sudo: required
services:
  - docker
script:
  - bundle exec rake lint
  - bundle exec rake validate
  - bundle exec rake beaker
matrix:
  include:
  - rvm: default
    env: BEAKER_set="debian-8-x86_64_docker"
  - rvm: default
    env: BEAKER_set="centos-7-x86_64_docker"